# Generated by Django 2.0 on 2017-12-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_path', models.CharField(db_index=True, max_length=100)),
                ('word', models.CharField(db_index=True, max_length=20)),
                ('tfidf_val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(null=True)),
                ('path', models.CharField(db_index=True, default='root', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('m_time', models.DateTimeField(null=True)),
                ('size', models.IntegerField(null=True)),
            ],
        ),
    ]
